# Generated by Django 4.2.2 on 2023-06-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('audionotes', models.FileField(blank=True, upload_to='Task/documents')),
                ('videonotes', models.FileField(upload_to='Task/documents')),
            ],
        ),
    ]
