# Generated by Django 4.2.2 on 2023-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='text',
        ),
        migrations.AddField(
            model_name='notes',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
