# Generated by Django 4.2.2 on 2023-06-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_notes_text_notes_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='note',
        ),
    ]
