# Generated by Django 4.2.2 on 2023-06-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_rename_notes_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='notes',
        ),
    ]
