# Generated by Django 4.2.2 on 2023-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_rename_note_notes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='audionotes',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='videonotes',
            field=models.FileField(upload_to='documents'),
        ),
    ]
